### ISSUE TITLE
Infinite scroll

### ISSUE THREAD

**Issue by danmichaelo** [scriptotek/realfagsbiblioteket-app#10]

**Comment by stianlagstad** [comment]
API'et ser ut til å gi samme resultat uavhengig av parameteren start dersom det ikke finnes flere bøker. Eksempel (query=lågstad, som bare har to treff):

https://scs.biblionaut.net/primo/search?institution=UBO&query=l%C3%A5gstad&start=1

https://scs.biblionaut.net/primo/search?institution=UBO&query=l%C3%A5gstad&start=10

https://scs.biblionaut.net/primo/search?institution=UBO&query=l%C3%A5gstad&start=999

Kan du se på det?
