### ISSUE TITLE
Skrive README

### ISSUE THREAD

**Issue by danmichaelo** [scriptotek/realfagsbiblioteket-app#13]
som f.eks. minner en på at en må kjøre `npm install` etter man har klonet repoet... for det glemte jeg nå.

**Comment by danmichaelo** [comment]
Hm, og så får jeg "No plugins added." etterpå. Var det noe mer man måtte kjøre?

**Comment by danmichaelo** [comment]
`ionic state reset` var den magiske kommandoen… Jeg tenker vi gjør som [her](http://stackoverflow.com/a/33459678/489916) og legger til dette i `postinstall` jeg.

**Comment by stianlagstad** [comment]
Close issue?

**Comment by danmichaelo** [comment]
README-en er fremdeles i korteste laget, men jeg kommer ikke på noe konkret som mangler, så det går
