### ISSUE TITLE
Should be possible to choose sorting in results list

### ISSUE THREAD

**Issue by danmichaelo** [scriptotek/realfagsbiblioteket-app#14]
I changed the default sorting to 'newest first', but it should be possible to switch to 'relevance' or 'title'.

**Comment by stianlagstad** [comment]
Tweak gjerne designet. https://github.com/scriptotek/realfagsbiblioteket-app/commit/f5963d7b26feb71505b12a8f5e9878ac0a7399d7

**Comment by stianlagstad** [comment]
Det beste hadde jo vært å bruke select

http://ionicframework.com/docs/components/#select

**Comment by danmichaelo** [comment]
Fixed in 2.3
