### ISSUE TITLE
Handle internet connection errors

### ISSUE THREAD

**Issue by stianlagstad** [scriptotek/realfagsbiblioteket-app#15]

**Comment by stianlagstad** [comment]
Users get a warning on launching app if they have no internet. Is that enough?

**Comment by danmichaelo** [comment]
We should expect internet to drop at any time really… All http requests should have a error handler.

As a user I might open the app, drive into a tunnel, then try to search for books about tunnels ;)

**Comment by stianlagstad** [comment]
Sjekk gjerne om dette er OK. Se også https://github.com/scriptotek/realfagsbiblioteket-app/commit/24b42a778e72c14bb07ed7a115ba2d4304c55b20
