### ISSUE TITLE
Intro tutorial

### ISSUE THREAD

**Issue by stianlagstad** [scriptotek/realfagsbiblioteket-app#17]
Like this: http://codepen.io/ionic/pen/AjgEB

**Comment by danmichaelo** [comment]
:+1:

**Comment by stianlagstad** [comment]
Status: Har slitt lenge, men får ikke til å legge inn innhold som går over skjerm-høyden. ion-slide vil ikke scrolle vertikalt, og jeg vil gjerne legge inn screenshots i introen som trenger plass i høyden. Se <http://codepen.io/anon/pen/zrdywr>.
