### ISSUE TITLE
Release 2.0

### ISSUE THREAD

**Issue by danmichaelo** [scriptotek/realfagsbiblioteket-app#20]
- [Ionic Publishing Guide](http://ionicframework.com/docs/guide/publishing.html) (dekker bare Android)
- [Play Developer Console](https://play.google.com/apps/publish/): @kyrretl og jeg har tilgang. Appen ligger under organisasjonen "Universitet i Oslo".
- http://xayin.com/thisisatest.html viser hvor "feature graphic", "promotional graphic" osv. brukes i Google Play
- [Deploy an Ionic app to the iOS App Store](https://medium.com/@_qzapaia/deploy-an-ionic-app-to-the-ios-app-store-702c79a2dd97)
- [Apple Developer](https://developer.apple.com/account/ios/identifiers/bundle/bundleList.action): Jeg får logga inn og sett appen selv uten Apple Developer Program.

Todo:

- [x] Sjekk at versjonsnummeret er satt til 2.0 alle steder
- [x] Sjekk metadata generelt i config.xml og andre steder

Todo Android:

- [x] Grave frem signeringsnøkkelen
- [x] High res icon: 512x512px: https://github.com/scriptotek/realfagsbiblioteket-app/blob/master/resources/icon.png
- [x] Screenshots: JPEG or 24-bit PNG. Min length for any side: 320px. Max length for any side: 3840px. At least 2 screenshots are required overall. Max 8 screenshots per type.
- [x] Feature graphic (now mandatory): 1024 w x 500 h. The feature graphic is shown at the top of the store listing and is a powerful tool to show off your app.
- [-] <s>Promotional graphic (optional): 180 w x 120 h</s>

Todo iOS:

- [x] Publisering på Apple Store krever Apple Developer Program som koster $99 årlig. @kyrretl hadde en konto, men den har antakelig ikke blitt fornyet?
  - [x] Sendt epost til Usit-Anders for å få mer info 2015-01-18
- [x] <s>Grave frem den gamle macen og sjekke om utviklingsmiljøet fortsatt funker. Mest sannsynlig må maskinen settes opp på nytt med nytt system og xcode, men da kan det være</s> det går raskere at vi bare bruker min Mac i stedet. I så fall bør vi antakelig ha Developer Program på min Apple ID.
- [x] Booke en time med USIT-Anders? Eller klarer vi oss uten? Ser ut som vi kan generere sertifikater på nytt
- [x] Screenshots: One screenshot per localization is required and up to 4 more are optional. For specifications of screenshots, read [Screenshot Properties](https://developer.apple.com/library/ios/documentation/LanguagesUtilities/Conceptual/iTunesConnect_Guide/Appendices/Properties.html#//apple_ref/doc/uid/TP40011225-CH26-SW2).
- [x] App icon: 1024 x 1024 pixels (no transparency, no rounded corners). Må antakelig eksporteres fra Illustrator-filen (fant den i mappen "Mørk blå")

**Comment by stianlagstad** [comment]
note to self: Bruk https://github.com/danmichaelo/cordova-plugin-appinfo

**Comment by stianlagstad** [comment]
![bok-lantanoider](https://cloud.githubusercontent.com/assets/4340859/12645394/1704ca7a-c5ca-11e5-8545-b8e199909de3.png)
![front](https://cloud.githubusercontent.com/assets/4340859/12645395/1706278a-c5ca-11e5-8414-abd499aa4497.png)
![sok-sola](https://cloud.githubusercontent.com/assets/4340859/12645396/1707d710-c5ca-11e5-9799-e3bee68c187c.png)

Ok som screenshots?

**Comment by danmichaelo** [comment]
Bra! Et bilde med kart også?

**Comment by stianlagstad** [comment]
Da må noen(tm) fikse kart først?

**Comment by danmichaelo** [comment]
høh, jeg trodde det virka?

**Comment by danmichaelo** [comment]
Kanskje jeg ikke snakka med deg om det. Vi fant ut at eksempelboken var i et magasin, der er det jo ikke kart.

**Comment by stianlagstad** [comment]
Kan du se om du kan finne en bok med et kart?

**Comment by stianlagstad** [comment]
Never mind! Se:

![bok-kart](https://cloud.githubusercontent.com/assets/4340859/12645493/a9cf8bec-c5ca-11e5-9e51-dd7322975fcb.png)

Ok?

**Comment by danmichaelo** [comment]
Jupp!

**Comment by stianlagstad** [comment]
Da er screenshots ok. Feature show er jeg usikker på. Tror ikke det blir fint om jeg lager det. Kan spørre Karoline?
