### ISSUE TITLE
No results for query "X": X oppdaterer seg når man skriver

### ISSUE THREAD

**Issue by danmichaelo** [scriptotek/realfagsbiblioteket-app#21]
`No results for query "X"`: `X` er bundet til tekstfeltet, så den oppdaterer seg når man skriver

**Comment by stianlagstad** [comment]
Kan du vise meg etterpå? Det fungerer fint her, både på mobil og med `ionic serve`.

**Comment by stianlagstad** [comment]
først gjør et søk uten resultater -> skriv ny søkestreng -> det skjer
