### ISSUE TITLE
External links don't work

### ISSUE THREAD

**Issue by danmichaelo** [scriptotek/realfagsbiblioteket-app#23]
Intet skjer ved trykk på  "Les online" for f.eks. "Svingninger og bølger" på en ekte Android-enhet (fra `ionic serve` funker det)

Ser ut som vi trenger inAppBrowser jfr. https://forum.ionicframework.com/t/opening-external-links-in-ionic/12265 , http://www.gajotres.net/how-to-launch-external-application-with-ionic-framework/ osv…

<s>`ngCordova` tilbyr en ryddig måte å injisere denne (og andre plugins): http://ngcordova.com/docs/plugins/inAppBrowser/</s> Den var der allerede :D

**Comment by stianlagstad** [comment]
Funker ikke hos meg. Trykker på linken men ingenting skjer. I console:
![lesmer](https://cloud.githubusercontent.com/assets/4340859/12475150/100e300c-c021-11e5-9728-85f040fafb92.png)

**Comment by danmichaelo** [comment]
På desktop eller mobil? Mistenker at det bare funker på mobil, ikke med `ionic serve`…

**Comment by stianlagstad** [comment]
Det åpna et nytt vindu i nettleseren med `ionic serve` - så det funka. Det skjedde ingenting på mobil.

**Comment by danmichaelo** [comment]
Urgh, skal teste

**Comment by stianlagstad** [comment]
Si ifra hvis du vil låne mobilen min for å teste.

**Comment by danmichaelo** [comment]
Er litt usikker på om jeg har fikset dette eller ikke. Kan du teste @stianlagstad ?

**Comment by stianlagstad** [comment]
Et nytt vindu åpnes, men jeg får en feilmelding som sier "No full text available" (exlibrisgroup.com) på boka jeg prøvde: Svingninger og bølger, Helmut Ormestad, 1964. Har du andre eksempelbøker? Jeg prøvde å finne en men det var useless.

**Comment by danmichaelo** [comment]
Prøv denne:

![book-with-ebook](https://cloud.githubusercontent.com/assets/434495/12814582/6c8e8866-cb40-11e5-833b-4a0195418a59.png)

**Comment by stianlagstad** [comment]
Kommer til en side som sier "Full text available at: <link>". Hvis det skal være sånn - all is well.

**Comment by danmichaelo** [comment]
Eeeh, det skulle helst stått "Full text available at: SpringerLink Books Complete" :) Ser på det neste gang du er innom
