### ISSUE TITLE
Barcode scanning broken?

### ISSUE THREAD

**Issue by danmichaelo** [scriptotek/realfagsbiblioteket-app#24]
Intet skjer når jeg trykker på scanne-knappen på min mobil (Android 5.1.1). Funker det på andre?

**Comment by stianlagstad** [comment]
Kan du vise meg etterpå? Det fungerer fint her, både på mobil og med `ionic serve`.

**Comment by stianlagstad** [comment]
Funker på min mobil. Sjekka console mens du prøver? chrome://inspect/#devices

**Comment by danmichaelo** [comment]
Hm, så det ser ikke ut til at npm klarer å hente `phonegap-plugin-barcodescanner` fra git automatisk. Den er jo definert i `package.json`, men jeg finner ikke dokumentasjon på `locator/id`-greiene under `cordovaPlugins`… så da får man bare kjøre

```
cordova plugin add https://github.com/phonegap/phonegap-plugin-barcodescanner.git
```

etterpå…
