### ISSUE TITLE
Åpne kart i fullskjerm når man trykker på det

### ISSUE THREAD

**Issue by danmichaelo** [scriptotek/realfagsbiblioteket-app#27]

**Comment by stianlagstad** [comment]
Jeg synes det funker greit. Vil du sjekke, @danmichaelo ? Kan legge på en div som viser collection_name og callcode kanskje

**Comment by danmichaelo** [comment]
Ja, gjør det. Bruk `position: fixed` for fast posisjon uavhengig av scroll, hvis du trenger det.
