### ISSUE TITLE
Legg til mulighet for å dele bøker

### ISSUE THREAD

**Issue by danmichaelo** [scriptotek/realfagsbiblioteket-app#28]
med http://ngcordova.com/docs/plugins/socialSharing/

**Comment by stianlagstad** [comment]
Kan du se på https://github.com/scriptotek/realfagsbiblioteket-app/commit/f603344fc4c03f678c57f6553338f4f9d97d1fb6 om det er ok?

**Comment by danmichaelo** [comment]
Ser ok ut. Jeg kan jobbe litt med teksten

**Comment by stianlagstad** [comment]
Tommel opp!

**Comment by danmichaelo** [comment]
Eller vent… det hadde ikke vært bedre å bruke "native sharing sheet"?

**Comment by danmichaelo** [comment]
Hvordan funker det å dele til instagram forresten....?

**Comment by stianlagstad** [comment]
For issue-comment-historiens skyld: Bruker native sharing sheet (se http://ngcordova.com/docs/plugins/socialSharing/), men har fire forskjellige ikoner som trigger funksjonen.

**Comment by danmichaelo** [comment]
:+1:

**Comment by danmichaelo** [comment]
Fixed in 2.3
