### ISSUE TITLE
Double escape of callnumber in book template

### ISSUE THREAD

**Issue by danmichaelo** [scriptotek/realfagsbiblioteket-app#33]
42-samlingen er den eneste med mellomrom i callnumber, derfor har vi ikke oppdaget det før. For bøker i denne samlingen blir det svarte kart fordi mellomrom blir dobbelescapa som `%25%20`:

https://app.uio.no/ub/bdi/bibsearch/new.php?collection=k00475&callnumber=FA%25204427

mens det skulle vært

https://app.uio.no/ub/bdi/bibsearch/new.php?collection=k00475&callnumber=FA%204427

**Comment by stianlagstad** [comment]
Har du et eksempel der det skjer? Jeg sjekka `app/view/BIBSYS_ILS71495594880002201`, som funker som den skal.

**Comment by danmichaelo** [comment]
Søk etter "urealsamling42", så får du alle bøkene i samlingen.

Kyrre gjorde forresten en hotfix i scriptet: erstatning av `%25%20` med `%20`, det er derfor den øverste lenken over virker.
